language: node_js

sudo: false
dist: trusty

node_js:
- node

cache:
  directories:
  - node_modules

env:
  global:
  - GIT_AUTHOR_NAME: Altaf Ali
  - GIT_AUTHOR_EMAIL: altaf@fastmail.com
  - secure: lXPGyK/HjakEseBhwGn7iuS/wH2hrMKILihutVEXIK1vamHA3y8wDufvYJPE3ZOVbAwyqXLhPJ2MNgQBGtIBm6B8uDxa8TWO8YP/S+p480329NNnqTriV+saWEvQmeriEILfnCuWJxuEo5z7rD7le7dO2Jga1VCw5lFf5XlO09S1T1l7rmU3wsztKLRLaPvBBo3g3NFmW8n+A2CvxYF4FczjRcge8O5H6uo5ma5AZA9OoLz8oupOkjwuWnUulOzRd/5yWbpuQDf4ordZFibPu1qxbLQUBfbShUwels+8x+tTP9BAO/3Bm27HRVTmowFuYQh5xvvJq/Qawf8I9b7WxIh9bZG5aFTUwHD7bTrKCnFbCtJlshVr8rWndkYQSmZ/7dWWTtAdOVnwSElg5uWUJ6SHa5u1LKzvhoExZL48q4ZaWv42ScdMIhFLIH5M6t9tQ5HC+r1zVlNiEH1sKLcFwxt/JA1rWDYjSPo9SzDUTkNhNQFrSuENdQINoK7iCax+uXp5CFSMugvhQpBRZ3Fb+ZYuI8PPacj+ZI6fEa8UjDZ2owOsVMdovI9CYkh8yhDz+LPu7XxRW3WpXEk+Ob6TWcUj392OcB0l0Ys0L59gOIWnr2zA+sdcg/k+MhKjYEpwHeShKvIkR9c3RxTsnBumIGFYiQ8z8qOM4Ks8Ju6XCgg=

notifications:
  email: false

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli-ghpages
- npm install --save angular/material2-builds angular/cdk-builds

script:
- ng build --prod --base-href "https://altaf-ali.github.io/sentry/"

